/*
 * Copyright (C) 2008-2012 TrinityCore <http://www.trinitycore.org/>
 *
 * Copyright (C) 2010-2015 QuantumCore <http://vk.com/quantumcore>
 *
 * Copyright (C) 2010-2012 MaNGOS project <http://getmangos.com>
 *
 */

#ifndef DEF_NEXUS_H
#define DEF_NEXUS_H

enum Types
{
    DATA_MAGUS_TELESTRA_EVENT,
    DATA_ANOMALUS_EVENT,
    DATA_ORMOROK_EVENT,
    DATA_KERISTRASZA_EVENT,

	DATA_MAGUS_TELESTRA,
    DATA_ANOMALUS,
	DATA_ORMOROK,
    DATA_KERISTRASZA,

    ANOMALUS_CONTAINMET_SPHERE,
    ORMOROKS_CONTAINMET_SPHERE,
    TELESTRAS_CONTAINMET_SPHERE,
};

enum Creatures
{
	NPC_GRAND_MAGUS_TELESTRA  = 26731,
	NPC_ANOMALUS              = 26763,
	NPC_ORMOROK               = 26794,
	NPC_KERISTRASZA           = 26723,
	NPC_CRYSTALINE_FRAYER     = 26793,
	NPC_WILTED_FRAYER         = 29911,
	NPC_ALLIANCE_BERSERKER    = 26800,
	NPC_HORDE_BERSERKER       = 26799,
	NPC_ALLIANCE_RANGER       = 26802,
	NPC_HORDE_RANGER          = 26801,
	NPC_ALLIANCE_CLERIC       = 26805,
	NPC_HORDE_CLERIC          = 26803,
	NPC_ALLIANCE_COMMANDER    = 27949,
	NPC_HORDE_COMMANDER       = 27947,
	NPC_COMMANDER_STOUTBEARD  = 26796,
	NPC_COMMANDER_KOLURG      = 26798,
    NPC_FIRE_MAGUS            = 26928,
    NPC_FROST_MAGUS           = 26930,
    NPC_ARCANE_MAGUS          = 26929,
	NPC_CRAZED_MANA_WRAITH    = 26746,
    NPC_CHAOTIC_RIFT          = 26918,
	NPC_CRYSTAL_SPIKE_INITIAL = 27101,
    NPC_CRYSTAL_SPIKE_TRIGGER = 27079,
	NPC_CRYSTALINE_TANGLER    = 32665,
};

enum Gameobjects
{
	GO_TELESTRA_SPHERE        = 188526,
	GO_ANOMALUS_SPHERE        = 188527,
	GO_OMOROK_SPHERE          = 188528,
	GO_CRYSTAL_SPIKE_TRAP     = 188537,
};

enum Achievements
{
	ACHIEVEMENT_INTENSE_COLD      = 2036,
	ACHIEVEMENT_CHAOS_THEORY      = 2037,
	ACHIEVEMENT_SPLIT_PERSONALITY = 2150,

};

enum Encounters
{
	MAX_ENCOUNTERS = 4,
};

#endif