/*
 * Copyright (C) 2008-2012 TrinityCore <http://www.trinitycore.org/>
 *
 * Copyright (C) 2010-2015 QuantumCore <http://vk.com/quantumcore>
 *
 * Copyright (C) 2010-2012 MaNGOS project <http://getmangos.com>
 *
 */

#ifndef DEF_AHNKAHET_H
#define DEF_AHNKAHET_H

enum Data64
{
    DATA_ELDER_NADOX,
    DATA_PRINCE_TALDARAM,
    DATA_JEDOGA_SHADOWSEEKER,
    DATA_HERALD_VOLAZJ,
    DATA_AMANITAR,
    DATA_SPHERE1,
    DATA_SPHERE2,
    DATA_PRINCE_TALDARAM_PLATFORM,
    DATA_PL_JEDOGA_TARGET,
    DATA_ADD_JEDOGA_OPFER,
    DATA_ADD_JEDOGA_INITIAND,
};

enum Data
{
    DATA_ELDER_NADOX_EVENT,
    DATA_PRINCE_TALDARAM_EVENT,
    DATA_JEDOGA_SHADOWSEEKER_EVENT,
    DATA_HERALD_VOLAZJ_EVENT,
    DATA_AMANITAR_EVENT,
    DATA_SPHERE1_EVENT,
    DATA_SPHERE2_EVENT,
    DATA_JEDOGA_TRIGGER_SWITCH,
    DATA_JEDOGA_RESET_INITIANDS,
    DATA_INITIAND_KILLED,
    DATA_ALL_INITIAND_DEAD,
};

enum Creatures
{
	NPC_AHNKAHAR_GUARDIAN  = 30176,
	NPC_AHNKAHAR_SWARMER   = 30178,
	NPC_HEALTHY_MUSHROOM   = 30391,
    NPC_POISONOUS_MUSHROOM = 30435,
    NPC_TRIGGER            = 19656,
	NPC_JEDOGA_CONTROLLER  = 30181,
	NPC_TWISTED_VISAGE     = 30625,
	NPC_FLAME_SPHERE       = 30106,
    NPC_FLAME_SPHERE_1     = 31686,
    NPC_FLAME_SPHERE_2     = 31687,
};

enum Gameobjects
{
	GO_SPHERE1  = 193093,
    GO_SPHERE2  = 193094,
};

enum Achievements
{
    ACHIEVEMENT_VOLUNTEER_WORK      = 2056,
	ACHIEV_QUICK_DEMISE_START_EVENT = 20382,
};

enum Encounters
{
	MAX_ENCOUNTER = 5,
};

#endif