/*
 * Copyright (C) 2008-2012 TrinityCore <http://www.trinitycore.org/>
 *
 * Copyright (C) 2010-2015 QuantumCore <http://vk.com/quantumcore>
 *
 * Copyright (C) 2010-2012 MaNGOS project <http://getmangos.com>
 *
 */

#ifndef DEF_UTGARDE_PINNACLE_H
#define DEF_UTGARDE_PINNACLE_H

enum Data
{
    DATA_SVALA_SORROWGRAVE_EVENT,
    DATA_GORTOK_PALEHOOF_EVENT,
    DATA_SKADI_THE_RUTHLESS_EVENT,
    DATA_KING_YMIRON_EVENT,
};

enum Data64
{
    DATA_SVALA,
    DATA_SVALA_SORROWGRAVE,
    DATA_GORTOK_PALEHOOF,
    DATA_SKADI_THE_RUTHLESS,
    DATA_MOB_GRAUF,
    DATA_KING_YMIRON,
    DATA_FRENZIED_WORGEN,
    DATA_RAVENOUS_FURBOLG,
    DATA_MASSIVE_JORMUNGAR,
    DATA_FEROCIOUS_RHINO,
    DATA_MOB_ORB,
    DATA_GORTOK_PALEHOOF_SPHERE,
    DATA_SACRIFICED_PLAYER,
};

enum Creatures
{
    NPC_SVALA_SORROWGRAVE    = 26668,
    NPC_GORTOK_PALEHOOF      = 26687,
    NPC_SKADI_RUTHLESS       = 26693,
    NPC_KING_YMIRON          = 26861,
    NPC_FRENZIED_WORGEN      = 26683,
    NPC_RAVENOUS_FURBOLG     = 26684,
    NPC_MASSIVE_JORMUNGAR    = 26685,
    NPC_FEROCIOUS_RHINO      = 26686,
    NPC_SVALA                = 29281,
	NPC_PALEHOOF_ORB         = 26688,
	NPC_YMIRJAR_WARRIOR      = 26690,
    NPC_YMIRJAR_WITCH_DOCTOR = 26691,
    NPC_YMIRJAR_HARPOONER    = 26692,
    NPC_GRAUF                = 26893,
    NPC_FLAME_BREATH_TRIGGER = 28351,
    NPC_MOUNT                = 27043,
	NPC_BJORN                = 27303,
    NPC_BJORN_VISUAL         = 27304,
    NPC_HALDOR               = 27307,
    NPC_HALDOR_VISUAL        = 27310,
    NPC_RANULF               = 27308,
    NPC_RANULF_VISUAL        = 27311,
    NPC_TORGYN               = 27309,
    NPC_TORGYN_VISUAL        = 27312,
    NPC_SPIRIT_FOUNT         = 27339,
    NPC_AVENGING_SPIRIT      = 27386,
	NPC_ARTHAS               = 29280,
    NPC_RITUAL_CHANNELER     = 27281,
    NPC_SPECTATOR            = 26667,
    NPC_RITUAL_TARGET        = 27327,
    NPC_FLAME_BRAZIER        = 27273,
    NPC_SCOURGE_HULK         = 26555,
	NPC_STASIS_CONTROLLER    = 26688,
	NPC_WORLD_TRIGGER        = 22515,
};

enum GameObjects
{
    GO_SKADI_THE_RUTHLESS_DOOR = 192173,
    GO_KING_YMIRON_DOOR        = 192174,
    GO_GORK_PALEHOOF_SPHERE    = 188593,
	GO_UTGARDE_MIRROR          = 191745,
};

enum AchievementData
{
	ACHIEV_TIMED_START_EVENT     = 17726,
    ACHIEVEMENT_GIRL_LOVES_SKADI = 2156,
	DATA_INCREDIBLE_HULK         = 2043,
};

enum Encounters
{
	MAX_ENCOUNTER = 4,
};

#endif